<Project Sdk="Microsoft.NET.Sdk.Web">
  <Import Project="..\..\Build.props" />
  <PropertyGroup>
    <ImplicitUsings>enable</ImplicitUsings>
    <OutputType>Library</OutputType>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\Libraries\SPTushonka.Common\SPTushonka.Common.csproj" />
    <ProjectReference Include="..\..\Libraries\SPTushonka.DI\SPTushonka.DI.csproj" />
    <ProjectReference Include="..\..\Libraries\SPTushonka.Reflection\SPTushonka.Reflection.csproj" />
    <ProjectReference Include="..\..\Libraries\SPTushonka.Server.Assets\SPTushonka.Server.Assets.csproj" />
    <ProjectReference Include="..\..\Libraries\SPTushonka.Server.Core\SPTushonka.Server.Core.csproj" />
    <ProjectReference Include="..\..\Libraries\SPTushonka.Server.Web\SPTushonka.Server.Web.csproj" />
  </ItemGroup>
  <ItemGroup>
    <Folder Include="wwwroot\" />
  </ItemGroup>
  <Target Name="CopyToServer" AfterTargets="PostBuildEvent">
    <ItemGroup>
      <OutputDLL Include="$(ProjectDir)$(OutDir)$(TargetName).dll" />
      <PrepatchDefinition Include="$(ProjectDir)TestPrepatch.json" />
      <Resources Include="$(ProjectDir)Resources\**\*.*" />
      <WebAssets Include="$(ProjectDir)wwwroot\**\*.*" />
    </ItemGroup>
    <!-- Copies the output dll -->
    <Copy
      SourceFiles="@(OutputDLL);"
      DestinationFolder="$(MSBuildProjectDirectory)\..\..\SPTushonka.Server\bin\$(Configuration)\net10.0\user\mods\TestMod2"
    />
    <Copy
      SourceFiles="@(PrepatchDefinition)"
      DestinationFolder="$(MSBuildProjectDirectory)\..\..\SPTushonka.Server\bin\$(Configuration)\net10.0\user\patchers\com.sp-tarkov.test-mod2"
    />
    <Copy
      SourceFiles="@(Resources);"
      DestinationFolder="$(MSBuildProjectDirectory)\..\..\SPTushonka.Server\bin\$(Configuration)\net10.0\user\mods\TestMod2\Resources\%(RecursiveDir)"
    />
    <!-- Copy the wwwroot folder -->
    <Copy
      SourceFiles="@(WebAssets)"
      DestinationFolder="$(MSBuildProjectDirectory)\..\..\SPTushonka.Server\bin\$(Configuration)\net10.0\user\mods\TestMod2\wwwroot\%(RecursiveDir)"
    />
  </Target>
</Project>
