<Project Sdk="Microsoft.NET.Sdk">
  <Import Project="..\..\Build.props" />
  <PropertyGroup>
    <PackageId>SPTushonka.DI</PackageId>
    <AssemblyName>SPTarkov.DI</AssemblyName>
    <RootNamespace>SPTarkov.DI</RootNamespace>
    <Authors>Single Player Tushonka</Authors>
    <Description>Dependency injection shared library for the Single Player Tushonka projects.</Description>
    <Copyright>Copyright (c) Single Player Tushonka 2026</Copyright>
    <PackageLicenseFile>LICENSE</PackageLicenseFile>
    <PackageProjectUrl>https://sp-mod.com</PackageProjectUrl>
    <RepositoryUrl>https://github.com/SP-Tushonka/server-csharp</RepositoryUrl>
    <ImplicitUsings>enable</ImplicitUsings>
    <OutputType>Library</OutputType>
    <IsPackable>true</IsPackable>
    <NoDefaultLaunchSettingsFile>true</NoDefaultLaunchSettingsFile>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="JetBrains.Annotations" Version="2026.2.0" />
    <PackageReference Include="Microsoft.Extensions.Hosting.Abstractions" Version="10.0.9" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" Version="10.0.9" />
  </ItemGroup>
  <ItemGroup>
    <None Include="..\..\LICENSE" Pack="true" Visible="false" PackagePath="" />
  </ItemGroup>
</Project>
