namespace QuestValidator.Common.Models
{
    public enum Quest
    {
        NOQUESTFOUND = 0,
        Debut = 1,
        BackgroundCheck = 2,
        ShootoutPicnic = 3,
        DeliveryFromThePast = 4,
        BadRepEvidence = 5,
        IceCreamCones = 6,
        PostmanPatP1 = 7,
        PostmanPatP2 = 8,
        ShakingUpTeller = 9,
        Shortage = 10,
        SanitaryStandardsP1 = 11,
        OperationAquarius = 12,
        OperationAquariusP2 = 13,
        Painkiller = 14,
        Pharmacist = 15,
        SupplyPlans = 16,
        KindOfSabotage = 17,
        GeneralWares = 18,
        SanitaryStandardsP2 = 19,
        CarRepair = 20,
        Supplier = 21,
        TheExtortionist = 22,
        Stirrup = 23,
        WhatsOnTheFlashDrive = 24,
        GoldenSwag = 25,
        PolikhimHobo = 26,
        ChemicalP1 = 27,
        ChemicalP2 = 28,
        ChemicalP3 = 29,
        ChemicalP4 = 30,
        OutOfCuriosity = 31,
        BigCustomer = 32,
        BPDepot = 33,
        ThePunisherP1 = 34,
        ThePunisherP2 = 35,
        ThePunisherP3 = 36,
        TrustRegain = 37,
        LoyaltyBuyout = 38,
        NoOffence = 39,
        ThePunisherP4 = 40,
        ThePunisherP5 = 41,
        ThePunisherP6 = 42,
        NoQuestNameGiven = 43,
        SpaTourP1 = 44,
        SpaTourP2 = 45,
        SpaTourP3 = 46,
        SpaTourP4 = 47,
        SpaTourP5 = 48,
        FishingGear = 49,
        TigrSafari = 50,
        ScrapMetal = 51,
        EagleEye = 52,
        HumanitarianSupplies = 53,
        TheCultP1 = 54,
        TheCultP2 = 55,
        SpaTourP6 = 56,
        SpaTourP7 = 57,
        CargoXP1 = 58,
        CargoXP2 = 59,
        CargoXP3 = 60,
        CargoXP4 = 246,
        WetJobP1 = 61,
        WetJobP2 = 62,
        WetJobP3 = 63,
        WetJobP4 = 64,
        WetJobP5 = 65,
        WetJobP6 = 66,
        FriendFromTheWestP1 = 67,
        FriendFromTheWestP2 = 68,
        HippocraticOath = 69,
        HealthCarePrivacyP1 = 70,
        HealthCarePrivacyP2 = 71,
        HealthCarePrivacyP3 = 72,
        HealthCarePrivacyP4 = 73,
        HealthCarePrivacyP5 = 74,
        GunsmithP1 = 75,
        GunsmithP2 = 76,
        GunsmithP3 = 77,
        GunsmithP4 = 78,
        GunsmithP5 = 79,
        GunsmithP6 = 80,
        FarmingP1 = 81,
        FarmingP2 = 82,
        FarmingP3 = 83,
        FarmingP4 = 84,
        SignalP1 = 85,
        SignalP2 = 86,
        SignalP3 = 87,
        SignalP4 = 88,
        BadHabit = 89,
        Scout = 90,
        Insider = 91,
        GunsmithP7 = 92,
        GunsmithP8 = 93,
        GunsmithP9 = 94,
        GunsmithP10 = 95,
        GunsmithP11 = 96,
        OnlyBusiness = 97,
        MakeUltraGreatAgain = 98,
        BigSale = 99,
        TheBloodOfWarP1 = 100,
        DressedToKill = 101,
        DatabaseP1 = 102,
        DatabaseP2 = 103,
        SewItGoodP1 = 104,
        SewItGoodP2 = 105,
        SewItGoodP3 = 106,
        SewItGoodP4 = 107,
        TheKeyToSuccess = 108,
        CharismaBringsSuccess = 109,
        NoFussNeeded = 110,
        Gratitude = 111,
        SalesNight = 112,
        Supervisor = 113,
        GunsmithP12 = 114,
        GunsmithP13 = 115,
        GunsmithP14 = 116,
        GunsmithP15 = 117,
        GunsmithP16 = 118,
        TheBloodOfWarP2 = 119,
        LivingHighIsNotACrimeP1 = 120,
        HotDelivery = 121,
        Minibus = 122,
        VitaminsP1 = 123,
        VitaminsP2 = 124,
        InformedMeansArmed = 125,
        LendLeaseP1 = 126,
        Chumming = 127,
        TheTarkovShooterP1 = 128,
        TheTarkovShooterP2 = 129,
        TheTarkovShooterP3 = 130,
        TheTarkovShooterP4 = 131,
        TheTarkovShooterP5 = 132,
        TheTarkovShooterP6 = 133,
        TheTarkovShooterP7 = 134,
        TheTarkovShooterP8 = 135,
        Bullshit = 136,
        SilentCaliber = 137,
        Insomnia = 138,
        TestDriveP1 = 139,
        Flint = 140,
        AShooterBornInHeaven = 141,
        PsychoSniper = 142,
        PrivateClinic = 143,
        Athlete = 144,
        LendLeaseP2 = 145,
        Grenadier = 146,
        DecontaminationService = 147,
        PeacekeepingMission = 148,
        TheGuide = 149,
        Fertilizers = 150,
        TheBloodOfWarP3 = 151,
        Scavenger = 152,
        LivingHighIsNotACrimeP2 = 153,
        Setup = 154,
        PerfectMediator = 155,
        Import = 156,
        Collector = 157,
        Introduction = 158,
        Acquaintance = 159,
        TheSurvivalistPathUnprotectedButDangerous = 160,
        TheSurvivalistPathThrifty = 161,
        TheSurvivalistPathZhivchik = 162,
        TheSurvivalistPathWoundedBeast = 163,
        TheSurvivalistPathToughGuy = 164,
        TheSurvivalistPathColdBlooded = 165,
        TheSurvivalistPathZatoichi = 166,
        TheSurvivalistPathEagleOwl = 167,
        TheSurvivalistPathCombatMedic = 168,
        TheSurvivalistPathJunkie = 169,
        HuntsmanPathSecuredPerimeter = 170,
        HuntsmanPathTheTrophy = 171,
        HuntsmanPathForestCleaning = 172,
        HuntsmanPathController = 173,
        HuntsmanPathSellOut = 174,
        HuntsmanPathWoodsKeeper = 175,
        HuntsmanPathJustice = 176,
        HuntsmanPathEvilWatchman = 177,
        HuntsmanPathFactoryChief = 178,
        HuntsmanPathEraserP1 = 179,
        HuntsmanPathEraserP2 = 180,
        HuntsmanPathSadist = 197,
        HuntsmanPathRelentless = 220,
        HuntsmanPathOutcasts = 240,
        Ambulance = 181,
        CourtesyVisit = 182,
        ShadyBusiness = 183,
        Nostalgia = 184,
        FishingPlace = 185,
        HuntingTrip = 186,
        Reserv = 187,
        RegulatedMaterials = 188,
        AnAppleADayKeepsTheDoctorAway = 189,
        Mentor = 190,
        TheStylishOne = 191,
        TextileP1Usec = 192,
        TextileP2Usec = 193,
        BunkerP1 = 194,
        BunkerP2 = 195,
        Anesthesia = 196,
        ColleaguesP1 = 198,
        ColleaguesP2 = 199,
        ColleaguesP3 = 200,
        RiggedGame = 201,
        Samples = 202,
        TerraGroupEmployee = 203,
        TheChemistryCloset = 204,
        SearchMission = 205,
        Hunter = 206,
        RevisionReserve = 207,
        PestControl = 208,
        BackDoor = 209,
        SafeCorridor = 210,
        InventoryCheck = 211,
        FuelMatter = 212,
        NoPlaceForRenegades = 213,
        DiseaseHistory = 214,
        Documents = 215,
        SurplusGoods = 216,
        ClassifiedTechnologies = 217,
        LongLine = 218,
        Booze = 219,
        SwiftOne = 221,
        TheChoice = 222,
        NightSweep = 223,
        Intimidator = 224,
        Crisis = 225,
        CapturingOutposts = 226,
        Escort = 227,
        Calibration = 228,

        // 229 free
        TextileP1Bear = 230,
        TextileP2Bear = 231,
        EasyJobPart1 = 232,
        EasyJobPart2 = 233,
        EnergyCrisis = 234,
        CommunicationDifficulties = 235,
        Overpopulation = 236,
        SeasideVacation = 237,
        CorporateSecrets = 238,
        Counteraction = 239,
        MissingCargo = 241,
        RevisionLighthouse = 242,
        OurOwnLand = 243,
        TheHermit = 244,
        LongRoad = 245,
        LostContact = 247,
        ActionTest = 248,
        CompensationForDamageTrust = 249,
        CompensationForDamageWager = 250,
        CompensationForDamageWergild = 251,
        CompensationForDamageCollection = 252,
        CompensationForDamageBarkeep = 253,
        DrugTrafficking = 254,
        Reconnaissance = 255,
        TopSecret = 256,
        BroadcastPart1 = 257,
        StrayDogs = 258,
        Trophies = 259,
        TheCleaner = 260,
        SpecialEquipment = 261,
        TheCourier = 262,
        EventLetters = 263,
        PopulationCensus = 264,
        UrbanMedicine = 265,
        HouseArrestPart1 = 266,
        HouseArrestPart2 = 267,
        Audiophile = 268,
        GloryToCPSUP1 = 269,
        BalletLover = 270,
        YouveGotMail = 271,
        YourCarNeedsAService = 272,
        Audit = 273,
        TestDriveP2 = 274,
        TheDeliciousSausage = 275,
        BroadcastPart3 = 276,
        Debtor = 277,
        GunsmithP17 = 278,
        GunsmithP18 = 279,
        GunsmithP19 = 280,
        GunsmithP20 = 281,
        GunsmithP21 = 282,
        GunsmithP22 = 283,
        CeaseFire = 284,
        KingsOfTheRooftops = 285,
        WatchingYou = 286,
        HarleyForever = 287,
        TheHuntsmanPathAdministrator = 288,
        GreenCorridor = 289,
        RevisionStreetsOfTarkov = 290,
        Surveillance = 291,
        NetworkProviderPart1 = 292,
        NetworkProviderPart2 = 293,
        AssessmentPart1 = 294,
        AssessmentPart2 = 295,
        AssessmentPart3 = 296,
        KeyToTheTower = 297,
        KnockKnock = 298,
        GettingAcquainted = 299,
        MakeAmendsBuyout = 300,
        MakeAmendsEquipment = 301,
        MakeAmendsSecurity = 302,
        MakeAmendsSweepUp = 303,
        MakeAmendsSoftware = 304,
        MakeAmendsQuarantine = 305,
        TotheTree = 306,
        BadSanta = 307,
        HomeComfort = 308,
        BroadcastPart2 = 309,
        Slaughterhouse = 310,
        DangerousRoad = 311,
        WorstJobInTheWorld = 312,
        BestJobInTheWorld = 313,
        BroadcastPart4 = 314,
        RoadClosed = 315,
        MakeAmends = 316,
        InformationSource = 317,
        MissingInformant = 318,
        Snatch = 319,
        Payback = 320,
        ReturnTheFavor = 321,
        Provocation = 322,
        FollowingTheBreadCrumbs = 323,
        Spotter = 324,
        MakeAnImpression = 325,
        TroubleInTheBigCity = 326,
        Bloodhounds = 327,
        Hint = 328,
        ImportantPatient = 329,
        FailedSetup = 330,
        Hustle = 331,
        Tourist = 332,
        CocktailTasting = 333,
        TerraGroupTrailP1 = 334,
        TerraGroupTrailP2 = 335,
        TerraGroupTrailP3 = 336,
        MakeAmendsP1 = 337,
        MakeAmendsP2 = 338,
        MakeAmendsP2Copy = 339,
        TerraGroupTrailP4 = 340,
        TerraGroupTrailP5 = 341,
        TerraGroupTrailP6 = 342,
        TerraGroupTrailP7 = 343,
        TerraGroupTrailP8 = 344,
        TerraGroupTrailP9 = 345,
        TerraGroupTrailP10 = 346,
        TerraGroupTrailP11 = 347,
        TerraGroupTrailP12 = 348,
        TerraGroupTrailP13 = 349,
        TerraGroupTrailP14 = 350,
        TerraGroupTrailP15 = 351,
        TerraGroupTrailP16 = 352,
        TerraGroupTrailP17 = 353,
        TerraGroupTrailP18 = 354,
        TerraGroupTrailP19 = 355,
        HuntsmanPathBigGame = 356,
        GendarmerieSchoolGuard = 357,
        GendarmerieMallCop = 358,
        GendarmerieTicketsPlease = 359,
        GendarmerieDistrictPatrol = 360,
        OutoOfTime = 361,
        BroadcastPart5 = 362,
        TheDoor = 363,
        OverseasTrustPart1 = 364,
        OverseasTrustPart2 = 365,
        AmbulancesAgain = 366,
        GloryToCPSUP2 = 367,
        SecretComponent = 368,
        TestDriveP3 = 369,
        BeyondTheRedMeatP1 = 370,
        BeyondTheRedMeatP2 = 371,
        PetsWontNeedItP1 = 372,
        GunsmithP23 = 373,
        GunsmithP24 = 374,
        GunsmithP25 = 375,
        ThePunisherHarvest = 376,
        ShootingCans = 377,
        FirstInLine = 378,
        BurningRubber = 379,
        SavingTheMole = 380,
        DevelopersSecretsP1 = 381,
        DevelopersSecretsP2 = 382,
        LuxuriousLife = 383,
        PyramidScheme = 384,
        PetsWontNeedItP2 = 385,
        PropertiesAllAround = 386,
        Dandies = 387,
        SteadySignal = 388,
        NothingFishyAboutThis = 389,
        HuntsmaPathCrookedCop = 390,
        NoSwiping = 391,
        EvilSpiritsEvent = 392,
        TheTarkovMystery = 393,
        DripOutP1 = 394,
        DripOutP2 = 395,
        TestDriveP4 = 396,
        Hustle2 = 397,
        EasyMoneyP1 = 398,
        EasyMoneyP2 = 399,
        BalancingP1 = 400,
        BalancingP2 = 401,
        Surprise = 402,
        CreateADistractionP1 = 403,
        CreateADistractionP2 = 404,
        ToGreatHeightsP1 = 405,
        ToGreatHeightsP2 = 406,
        ToGreatHeightsP3 = 407,
        ToGreatHeightsP4 = 408,
        ToGreatHeightsP5 = 409,
        AKeyToSalvation = 410,
        ThirstyHounds = 411,
        ThirstyBreadwinner = 412,
        ImportControl = 413,
        DripOutP1Bear = 414,
        DripOutP2Bear = 415,
        WhatsYourEvidence = 416,
        CaughtRedHanded = 417,
        RisksOfSmallBusiness,
        ProtectionOfInterests,
        TimeTested,
        WesternQualityStandards,
        HighCompetition,
        BadFeeling,
        GunsmithSpecialOrder,
        GunConnoisseur,
        CustomerCommunication,
        SupplyAndDemand,
        OneLessLooseEnd,
        AHealthyAlternative,
        ExitHere,
        Claustrophobia,
        Possessor,
        BlackSwan,
        HealthCarePrivacyP6,
        RoughTarkov,
        ForklistCertified,
        EveryHunterKnowsThis,
        PMCsBestFriend,
        Traveler,
        KillerOfKillers,
        TheWallsHaveEyes,
        AllIsRevealed,
        Dragnet,
        CapacityCheck,
        TestDriveP5,
        NewDayNewPath,
        KnowYourPlace,
        SecretsOfPolikhim,
        SpecialComms,
        ForestersDuty = 450,
        BeneathTheStreets,
        IsThisAReference,
        IntoTheInferno,
        InAndOut,
        OursByRight,
        ProvideCover,
        CreamOfTheCrop,
        BeforeTheRain,
        DontBelieveYourEyes,
        DirtyBlood,
        BurnItDown,
        TheRootCause,
        MatterOfTechnique,
        Irrestible,
        BreathingRoom,
        FriendFromNorvinskPart5,
    }
}
