blank_issues_enabled: false
contact_links:
  - name: Discord Community
    url: https://discord.sp-tushonka.com
    about: Find community support through our Discord server.
  - name: Github Discussions
    url: https://github.com/SP-Tushonka/server-csharp/discussions
    about: Please discuss the project on the Github Discussions board.
