using System.Text.Json.Serialization;
using SPTarkov.Server.Core.Models.Common;

namespace SPTarkov.Server.Core.Models.Eft.Quests;

/// <summary>
///     Which quests set the members of one variable group. Generated by the QuestVariableGenerator
/// </summary>
public record QuestVariableGroup
{
    [JsonPropertyName("id")]
    public required MongoId Id { get; set; }

    /// <summary>Quest to the exact member its completion sets.</summary>
    [JsonPropertyName("quests")]
    public required Dictionary<MongoId, MongoId> Quests { get; set; }

    /// <summary>Members whose quest is unknown, with the quests that could set them.</summary>
    [JsonPropertyName("fillers")]
    public required List<QuestVariableFillers> Fillers { get; set; }

    /// <summary>Quests gated on the group whose completion sets none of its members.</summary>
    [JsonPropertyName("notMembers")]
    public required List<MongoId> NotMembers { get; set; }
}

/// <summary>Completing any of the quests fills one of the members, up to the count.</summary>
public record QuestVariableFillers
{
    [JsonPropertyName("members")]
    public required int Members { get; set; }

    [JsonPropertyName("quests")]
    public required List<MongoId> Quests { get; set; }
}
