<Project Sdk="Microsoft.NET.Sdk">
  <Import Project="..\..\Build.props" />
  <PropertyGroup>
    <ServerGarbageCollection>true</ServerGarbageCollection>
    <EnableDefaultContentItems>false</EnableDefaultContentItems>
    <ImplicitUsings>enable</ImplicitUsings>
    <OutputType>Exe</OutputType>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\Libraries\SPTushonka.Server.Core\SPTushonka.Server.Core.csproj" />
    <ProjectReference Include="..\..\Libraries\SPTushonka.Server.Assets\SPTushonka.Server.Assets.csproj" />
    <ProjectReference Include="..\..\Libraries\SPTushonka.Common\SPTushonka.Common.csproj" />
    <ProjectReference Include="..\..\Libraries\SPTushonka.DI\SPTushonka.DI.csproj" />
  </ItemGroup>
</Project>
